version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: trecord-mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=trecord
      - MYSQL_ROOT_PASSWORD=1234

  redis:
    image: redis:latest
    container_name: trecord-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "1234" ]