spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mariadb://localhost:3306/trecord
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: HEADERS

jwt:
  secret-key: "adZw12pxc55CmnIKsNP42KIa+M+bTlezcJKs3sW2RctO"
  token.expired-time-ms: 86400000

google:
  client-id: "client id"
  client-secret: "client secret"
  oauth2:
    endpoint: "https://oauth2.googleapis.com"
  api:
    baseUrl: "https://www.googleapis.com"
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

google:
  oauth2:
    endpoint: "http://localhost:8089"
  api:
    baseUrl: "http://localhost:8089"
