spring.datasource:
  url: ${aws.rds.hostname}
  driver-class-name: org.mariadb.jdbc.Driver
  username: ${aws.rds.username}
  password: ${aws.rds.password}

spring.data:
  redis:
    url: ${SPRING_REDIS_URL}

jwt:
  secret-key: ${jwt.secret.key}

google:
  client-id: ${google.client.id}
  client-secret: ${google.client.secret}
