spring.profiles.default: local

spring.datasource:
  url: jdbc:mariadb://localhost:3306/trecord
  driver-class-name: org.mariadb.jdbc.Driver
  username: root
  password: 1234

spring.jpa:
  open-in-view: false

spring.data:
  redis:
    url: redis://:1234@localhost:6379

feign:
  client.config.default:
    connectTimeout: 1000
    readTimeout: 3000
    loggerLevel: HEADERS

jwt:
  secret-key: "adZw12pxc55CmnIKsNP42KIa+M+bTlezcJKs3sW2RctO"
  token-expired-time-ms: 86400000

google:
  client-id: "This is secret value"
  client-secret: "This is secret value"
  oauth2.endpoint: "https://oauth2.googleapis.com"
  api.baseUrl: "https://www.googleapis.com"
---
spring.config.activate.on-profile: local

spring.jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  properties:
    hibernate:
      format_sql: true